### ISSUE TITLE
Can't add a brand to auctioneer because of no PA

### ISSUE THREAD

**Issue by Jorge-Lopes** [Jorge-Lopes/arbitrage-bot-test-env#6]
# Goal: identify how to access the priceAuthorityAdmin

## Strategy 1:
- build a new core-eval for the fakeAtom auction based on the [price-feed-core.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/builders/scripts/inter-protocol/price-feed-core.js) and [price-feed-proposal.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/src/proposals/price-feed-proposal.js).
- The permit and script generated was the same as before.

## Strategy 2:
- Update the proposal builder scripts to produce an `priceFeedKit` and register the priceAuthority and priceAuthorityAdmin [price-feed-proposal](https://github.com/anilhelvaci/vaults-liquidation-bot/blob/feature/testing-setup/auctioneerTestingSetup/src/proposals/price-feed-proposal.js#L179)

- Then create a proposal builder script to consume the priceFeedKit  [getPriceAuthority-proposal.js](https://github.com/anilhelvaci/vaults-liquidation-bot/blob/feature/testing-setup/auctioneerTestingSetup/src/proposals/getPriceAuthority-proposal.js#L12) and logged on terminal using the script [getPriceFeedKit.js](https://github.com/Jorge-Lopes/arbitrage-bot-test-env/blob/develop/scripts/getPriceFeedKit.js)

### Issue
The priceFeedKit promise is never resolved

**Comment by anilhelvaci** [comment]
The problem was that we had to create a new price authority with the correct brands so the auctioneer could find it in the registry. See https://github.com/Agoric/agoric-sdk/blob/4df6e758409e9196fdf0381904a4caccec99545d/packages/inter-protocol/src/proposals/addAssetToVault.js#L109 for reference.
